### ISSUE TITLE
use it with new babel?

### ISSUE THREAD

**Issue by jkone27** [finom/babel-plugin-transform-es2015-modules-simple-amd#11]
i am trying to use the plugin but get this error

```
error [ERR_MODULE_NOT_FOUND]: Cannot find package 'babel-preset-transform-es2015-modules-simple-amd' imported from /Users/admin/Repositories/fe-js-tests/durandaljs/babel-virtual-resolve-base.js
```

**Comment by finom** [comment]
Sorry, the project isn't maintained anymore :(

**Comment by jkone27** [comment]
it was my niewbie mistake, i put it in presets instead of plugins :) it works!

would be cool just to provide this simpler alternative for AMD module sugar 

```
define(['knockout', './oneService'], function (ko, sayHello) {
```

becomes

```
define(function (require) {
     var ko = require('knockout);
     var sayHello = require('./oneService');
```

you think i could do it "easilly" based on this codebase?
