### ISSUE TITLE
Is babel-template a dependency?

### ISSUE THREAD

**Issue by tomwayson** [finom/babel-plugin-transform-es2015-modules-simple-amd#2]
I get this error after npm installing and using this plugin (via grunt-babel) in my project:

```
Warning: Cannot find module 'babel-template' Use --force to continue.
```

After running `npm install --save-dev babel-template` the plugin worked (very clean output by the way). Should babel-template be a dependency instead of a devDependency of this module?

**Comment by finom** [comment]
@tomwayson thank you. I guess the problem is because of NPM 3 is used by the plugin (but I need to check).

**Comment by finom** [comment]
@tomwayson you were right, thanks.

**Comment by tomwayson** [comment]
Just tried 0.2.1 (after removing babel-template as a dev dep from my repo) and it works perfectly. Thanks!

**Comment by finom** [comment]
@tomwayson awesome :)
