### ISSUE TITLE
[feature request] support for non-default exports / imports

### ISSUE THREAD

**Issue by dgoldstein0** [finom/babel-plugin-transform-es2015-modules-simple-amd#3]
It would be really cool if this could support non-default exports / destructuring-style imports, e.g.

foo.js

```
export function a(){...};
export function b(){...};
```

bar.js

```
import {a, b} from foo;
```

or at least support it with a syntax like

foo.js

```
export default {a: function(){...}, b: function(){...}};
```

I imagine this would come with the restriction that no module compiled with this plugin could have both an `export default` and named exports - even though that's technically allowed by the ES6 spec.

Why I want this: I work on a fairly sizeable coffeescript / AMD codebase, and we are looking to migrate to ES6.  We were going to use babel-plugin-transform-es2015-modules-amd, but the problem we found with it is that our coffeescript modules do not understand it's version of default exports - they are not going to `.default` anything without modification, which makes incremental upgrading hard for some of our modules.  I was very happy to see this plugin which does default exports the way I wanted, but we also have a penchant for using destructuring on coffeescript imports and I would like to be able to use `import {...} from foo` as an alternative to that; the few ES6 modules we've written so far already make use of this syntax.

**Comment by finom** [comment]
``` js
import {a, b} from foo;
```

This syntax makes sense and I will definitely do it. Unfortunately I'm not sponsored dev and I don't have enough time to close this issue quickly. Thank you for your message.

**Comment by dgoldstein0** [comment]
actually after reading about ES6 imports some more I'm not sure this is
even supposed to work this way - my reading of a bunch of ES6 blogs / docs
seems to suggest this syntax is for importing named imports, not
destructuring the default import.  Doesn't mean it wouldn't be useful
though.

**Comment by finom** [comment]
@dgoldstein0 have you checked it?
