### ISSUE TITLE
Transform class definitions into declare statements for Dojo

### ISSUE THREAD

**Issue by andrewfinnell** [finom/babel-plugin-transform-es2015-modules-simple-amd#4]
This plugin was a lifesaver for being able to use the import/export syntax with an AMD loader. However, Dojo had decided to use a special function to create 'classes' called declare. It seems rather easy, if not tedius, to convert ClassDefinitions and ClassExtensions into dojo compatible calls. 

Possible Solution: 

``` json
{
    "plugins": [
        [
            "transform-es2015-modules-simple-amd",
            {
                "classes": true,
                "target": "dojo"
            }
        ]
    ]
}
```

**Input.js**

``` js
import _WidgetBase from "dijit/_WidgetBase"

export default class extends _WidgetBase {
    constructor() {
        super();
    }
}
```

**Input-compiled.js**

``` js
"use strict";
define(["dojo/_base/declare", "dijit/_WidgetBase"], function (declare, _WidgetBase) {
    return declare([_WidgetBase], {
        constructor: function (args) {
            this.inherited(args);
        }
    });
});
//# sourceMappingURL=dojo-test.js.map
```

**Comment by andrewfinnell** [comment]
I'll look into what it might take to make these changes. I believe this type of feature would be killer for anyone working with AMD loaders and any other framework which defines classes uniquely. React, Angular, Dojo, etc.

**Comment by finom** [comment]
@afinnell custom class syntaxes are outdated as an idea. React got support of ES classes long time ago and React.createClass thing used only by oldfags. I'm not familiar with dojo but definitely they need to support ES classes as other libraries do.

Also, I'm not going to include any other transformer to this project. It's only about imports/exports, not about classes and other things.
