### ISSUE TITLE
import Default, {others..} not supported

### ISSUE THREAD

**Issue by smcmurray** [finom/babel-plugin-transform-es2015-modules-simple-amd#7]
```
import Default, {Other} from 'module'
```

causes TypeError: Cannot read property 'name' of undefined
    at babel-plugin-transform-es2015-modules-simple-amd/dist/index.js:63:151

using version 0.3.0

```
import {default as Default, Other} from 'module'
```

works

**Comment by finom** [comment]
@smcmurray thank you but the project is no longer maintained.
